version: "3"

services:
    app:
        container_name: desafios-front-senai
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
          - .:/app